services:
  - type: web
    name: ai-meeting-summarizer
    env: python
    buildCommand: |
      cd backend
      pip install -e .
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./app.db
      - key: HUGGINGFACE_CACHE_DIR
        value: /opt/render/project/src/backend/.cache/huggingface
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONPATH
        value: /opt/render/project/src 